### ISSUE TITLE
StackedArea: Tooltips should not show interpolated values

### ISSUE THREAD

**Issue by pabloarosado** [owid/owid-grapher#2866] opened 2023-10-27 11:12 UTC
## Description

Stacked area charts shows interpolated values that are not in the data.

## Expected behaviour

Stacked area charts, like line charts, linearly interpolate between consecutive values. From a data viz perspective, it's unclear whether this is wanted or not (and requires discussion). But they should never show interpolated values as if they were real data values.

## Steps to reproduce

1. Go to this URL https://ourworldindata.org/grapher/energy-consumption-by-source-and-country?country=~BLR
2. Hover over any point between 2000 and 2019.
3. See that nuclear shows some data values, but they shouldn't, since there's no data for Belarus' nuclear consumption between 2000 and 2019.

**NOTE**:  I changed the data so that Belarus's nuclear consumption between 2000 and 2019 is zero instead of nan. This "fixes" the problem. With nans, what you'd see is the linearly interpolated values between 2000 and 2019 as if they were real values. So currently I don't have any example to reproduce the behaviour (and if I see one, I manually fix the problem in the data, to avoid spurious interpolated values).

## Additional context

See [discussion on Slack](https://owid.slack.com/archives/C46U9LXRR/p1698401249045499).

**Comment by larsyencken** [comment] 2023-12-06 16:51
In this example, it looks like there are 0% values for each year when perhaps ideally there'd be NA values.

It appears to be happening somewhere in the table transform that the NAs get filled in, so it's earlier than at the tooltip level; the table view also shows 0 values for Belarus over that period.

A broader issue seems to be whether or not we should show stacking at all with NAs, for percentage values, in scenarios where we can't assume the NAs are zero.

**Comment by larsyencken** [comment] 2023-12-06 16:55
Marking this as "nice to have" given then difficulty of fixing it

**Comment by pabloarosado** [comment] 2023-12-07 07:54
> In this example, it looks like there are 0% values for each year when perhaps ideally there'd be NA values.
> 
> It appears to be happening somewhere in the table transform that the NAs get filled in, so it's earlier than at the tooltip level; the table view also shows 0 values for Belarus over that period.
> 
> A broader issue seems to be whether or not we should show stacking at all with NAs, for percentage values, in scenarios where we can't assume the NAs are zero.

Hi @larsyencken, sorry, that's actually not what happens. I changed the data to avoid showing spurious values. The chart used to show linearly interpolated values between 0 (value at year 2000) and 0.30 (value at year 2020), as if they were real values.
That, to me, is inacceptable: It's showing made up data as if they were real value.
Given that we didn't have a technical solution in place, I filled those nans with zeros.
I just updated the description of the issue, but, unfortunately, I don't have any example to show (and if I see one, I'll try to fix it by filling nans with zeros!).

**Comment by pabloarosado** [comment] 2023-12-07 08:15
Also, note that in [this case](https://ourworldindata.org/grapher/energy-consumption-by-source-and-country?stackMode=absolute&country=~BLR), filling with zeros is fine, because the real data should be zero ([there was no nuclear power in Belarus until 2020](https://world-nuclear.org/information-library/country-profiles/countries-a-f/belarus.aspx)). 

However, if that was not the case (imagine that there was nuclear, but we simply did not know the values, and therefore they were nan). Ideally, the chart would show "missing data" during those years. But currently, grapher would show a linearly increasing amount of nuclear power. In that case, filling with zeros would also be misleading, so we would have no solution (but to not use stacked area charts).

**Comment by larsyencken** [comment] 2023-12-07 12:22
> Also, note that in [this case](https://ourworldindata.org/grapher/energy-consumption-by-source-and-country?stackMode=absolute&country=~BLR), filling with zeros is fine, because the real data should be zero ([there was no nuclear power in Belarus until 2020](https://world-nuclear.org/information-library/country-profiles/countries-a-f/belarus.aspx)).
> 
> However, if that was not the case (imagine that there was nuclear, but we simply did not know the values, and therefore they were nan). Ideally, the chart would show "missing data" for nuclear during those years. But currently, grapher would show a linearly increasing amount of nuclear power. In that case, filling with zeros would also be misleading, so we would have no solution (but to not use stacked area charts).

Showing any stacking at all would be misleading for those years in that case, because the stacks are percentages of a whole, and the whole is unknown if any part of it is unknown. In non-percentage cases, it could still make sense to show a partial stack though. 

That suggests that the Stacked Area should have an option of what to do in the case of missing data, and in either case it should not show interpolated data as if it was a measured data point.

**Comment by sophiamersmann** [comment] 2023-12-19 10:56
@pabloarosado Do you know of an indicator I could use to reproduce this bug? Or could you maybe make one available for me? That would make it much easier for me to look into this :)

**Comment by pabloarosado** [comment] 2023-12-19 10:59
> @pabloarosado Do you know of an indicator I could use to reproduce this bug? Or could you maybe make one available for me? That would make it much easier for me to look into this :)

I don't know any case (I have tried to fix all I found). If you have a branch I can create one chart for you with the issue on the temporary staging server. Would that help?

**Comment by sophiamersmann** [comment] 2023-12-19 11:15
Yes, let's try that. Here is a staging server I just created: http://staging-site-fix-tooltip-interpolated-values/

**Comment by pabloarosado** [comment] 2023-12-19 11:39
I have just pushed some changes to the data of the Statistical Review of World Energy to that staging server. Now you can reproduce the issue mentioned in the description ([this chart](http://staging-site-fix-tooltip-interpolated-values/admin/charts/648/edit)): Belarus has no nuclear data between 2000 and 2019, but you see linearly interpolated values.

**Comment by sophiamersmann** [comment] 2023-12-19 13:31
Thank you!

**Closed** 2024-01-03 12:00 UTC
Labels: bug, tricky, viz, priority 2 - important, correctness
