### ISSUE TITLE
While installing the owid-catalog library getting library conflicts

### ISSUE THREAD

**Issue by PriyanshuRj** [owid/owid-grapher#1400] opened 2022-04-19 12:36 UTC
## Description

While installing the owid-catalog library for testing the the pythonic API's the installation didn't completed and getting dependencies based errors.

## Expected behaviour
The Library should have been installed correctly 

## Steps to reproduce

1. Install the owid-catalog library using the `pip install owid-catalog ` command.

## Screenshots
![Screenshot_20220419_233308](https://user-images.githubusercontent.com/76838551/164004415-b3a386d0-20dc-449b-9635-1ff82b03ffca.png)
![2](https://user-images.githubusercontent.com/76838551/164004643-33d17f94-9c9b-4566-adfd-8ec8af5de010.png)

## Environment

For desktop :

 - Operating System: Manjaro Linux
 - Kernel Version: 5.15.32-1-MANJARO (64-bit)

**Comment by danielgavrilov** [comment] 2022-04-19 17:35
- Closing since the issue is already reported in the other repo: https://github.com/owid/owid-catalog-py/issues/33

**Closed by danielgavrilov** 2022-04-19 17:35 UTC
Labels: bug, needs triage
