### ISSUE TITLE
Links in GDocs are rendered as split into two links when there is a subscript 2 inside the text

### ISSUE THREAD

**Issue by pabloarosado** [owid/owid-grapher#2962] opened 2023-11-29 14:53 UTC
## Description

Links in GDocs are rendered as split into two links when there is a subscript 2 inside the text

## Expected behaviour

[This GDoc](https://docs.google.com/document/d/1Gn3qu426Dme0QrbfOEheBH7DiE0JtZKyliGYDHfbLos/edit) contains the sentence:

> Trade-adjusted emissions can be found in [our CO2 Data Explorer](https://ourworldindata.org/explorers/co2?tab=map&facet=none&country=CHN~USA~IND~GBR~OWID_WRL&Gas+or+Warming=CO%E2%82%82&Accounting=Consumption-based&Fuel+or+Land+Use+Change=All+fossil+emissions&Count=Per+capita).

But the rendered document shows two links (possibly three) instead of one, separated at the subscript 2:
![Screen Shot 2023-11-29 at 15 51 59](https://github.com/owid/owid-grapher/assets/12246978/62ac14a5-2829-41ac-86a6-c94d2d7f9482)

**Comment by mlbrgl** [comment] 2024-01-23 14:52
@danyx23 @ikesau triaged

**Comment by ikesau** [comment] 2024-10-08 15:51
Duplicate of https://github.com/owid/owid-grapher/issues/2842

**Closed by ikesau** 2024-10-08 15:51 UTC
Labels: bug, site, priority 3 - nice to have, internal-onboarding
