### ISSUE TITLE
Entity selector: Sort entities by value by default

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#4265] opened 2024-12-06 09:20 UTC
For single y-indicator charts (including scatter plots), sort entities by value by default in the entity selector.
For charts with multiple y-indicators (e.g., stacked area charts), keep sorting entities alphabetically since picking one indicator would be awkward.

This is something that came out of Bobbie's session replay, and we discussed it in a data viz meeting with Marwa present.

**Comment by danyx23** [comment] 2024-12-19 09:56
Duplicate of #4202

**Closed by danyx23** 2024-12-19 09:56 UTC
Labels: feature, viz, needs triage
