### ISSUE TITLE
Split by country option disappears if a short axis unit is added and relative values is off

### ISSUE THREAD

**Issue by saloni-nd** [owid/owid-grapher#2939] opened 2023-11-24 11:25 UTC
## Description
Split by country isn't shown if a short axis unit is added, unless relative values is on.

## Expected behaviour

I expected split by country to be available regardless of having a short axis unit, and regardless of having relative values.

## Steps to reproduce and screenshots

This [chart](https://owid.cloud/admin/charts/7378/edit) has weird behaviour when I enter a short axis unit – the 'split by country' option disappears, and it switches to 'split by metric'.

After that, if I turn on 'relative values', then 'split by country' shows up again.

## Screenshots

**Initial chart:**

<img width="996" alt="image" src="https://github.com/owid/owid-grapher/assets/31684905/6a829023-ede0-40c6-a200-2cd69b52e0df">

If I add a short axis unit, it switches automatically to 'split by metric':

<img width="999" alt="image" src="https://github.com/owid/owid-grapher/assets/31684905/6b853de5-db34-4e83-b0de-ef5d49ec4e5a">

And the 'split by country' option disappears:

<img width="999" alt="image" src="https://github.com/owid/owid-grapher/assets/31684905/8cbfbb64-84ff-462d-92aa-2b58e88078fa">

But if I turn on 'relative values', then the 'split by country' option shows up again:

<img width="996" alt="image" src="https://github.com/owid/owid-grapher/assets/31684905/06d0eccf-f754-49b0-89b9-de6d6643eaa8">

## Screen capture video

Not sure if I can upload a video here but maybe it works:

https://github.com/owid/owid-grapher/assets/31684905/413490bb-73ad-41c2-9ccf-60d014eb598f

## Environment

In owid.cloud

**Comment by danyx23** [comment] 2024-02-14 15:50
@saloni-nd this took us a while to understand but what is going on here is that by changing the short unit of just one indicator you are making them "not the same". If you set the same short unit on all indicators, the split by country option becomes the default again and it works as intended. 

This is admittedly hard to understand but it's not clear to us how best to avoid this - we probably need this check to make sure that showing the data facetted like this is sensible in the first place. As such, I'll close it as wont-fix and we'll have to try to educate others about this.

**Closed by danyx23** 2024-02-14 15:50 UTC
Labels: bug, viz
