### ISSUE TITLE
Grapher: Unable to type non-integer values into the 'unit conversion factor' box in grapher admin

### ISSUE THREAD

**Issue by spoonerf** [owid/owid-grapher#1636] opened 2022-09-06 10:03 UTC
## Description

In the grapher admin you are no longer able to type non-integer values into the 'Unit conversion factor' box (within the variable dropdown). It is possible to copy and paste '0.01' for example, but it is not possible to type it. 

## Expected behaviour

You should be able to type any numeric value into this box. 

## Steps to reproduce

1. Go to this URL - https://owid.cloud/admin/charts/5942/edit
2. Click on ' the the 'v' button to open up one of the variables e.g. 'Infant mortality rate'
3. Scroll down to 'Unit conversion factor'
4. Try and type '0.01'
5. See error

**Comment by danyx23** [comment] 2022-09-13 11:21
Closing this issue as duplicate of #1427

**Closed by danyx23** 2022-09-13 11:21 UTC
Labels: bug, needs triage
