### ISSUE TITLE
Easy way to avoid stroboscopic data ink flashing

### ISSUE THREAD

**Issue by monfera** [owid/owid-grapher#868] opened 2021-04-26 20:17 UTC
Hi folks,

there's an approx. 1px gap vertically between the capture zones of line annotations, which causes this flash. 
Reducing the vertical offset by 1px, or adjusting CSS padding, margin or invisible border would yield a vastly better experience in this regard. Very small change for significant impact. There might be subtleties you as implementors are privy of; if you're busy or not aware of such subtleties, pls. reply and I can triage the issue and maybe patch

https://user-images.githubusercontent.com/1548516/116142634-6d31e580-a6da-11eb-9654-b94c226a65aa.mp4

The specific selector may be `g.LineLabels > g.legendMark > rect` and/or `g.LineLabels > g.legendMark > text`

P.S. turns out, the above screen capture doesn't show the brief flashes most of the time, maybe this:

https://user-images.githubusercontent.com/1548516/116145301-77091800-a6dd-11eb-9625-b0a49744a461.mp4

**Comment by danyx23** [comment] 2021-05-24 08:34
Hi Robert, thanks a lot for reporting this issue! Sorry it took so long to get back to you, we had a couple of people leaving and new ones coming onboard on the tech team and we are still getting all the processes sorted out. 

I looked at this and agree that the flashing is ugly. I couldn't reproduce the issue on Firefox on Windows, only on Chromium based browsers, so it may have to do with rounding of values for event target collision detection. I tried a couple of quick fixes but unfortunately wasn't able to fix this issue yet. I'll discuss it with my colleagues and we'll triage the issue at our next team meeting.

**Comment by monfera** [comment] 2021-05-24 12:08
Thanks @danyx23! I can confirm that Safari and FF on OS X also behave well. With this new test, I noticed that still the entire dataset is shown in the gaps where the line labels are not placed as densely. 

It's not the original topic of this gh item, yet I wonder if the experience would be improved by picking the closest label, instead of leaving gaps. This could be achieved by eg. appropriately sizing a varying top/bottom padding, or doing an 1D voronoi test if you map the mouse `y` values to highlighted labels in JS, rather than via DOM event capture. The renderer already needs to know the vertical label positions, so the data is there to compute the midpoints. This way, when the user hovers over the line label column, it would only ever saliently show one line (whicever is closest to the mouse). 

With or without this, the Chrome fix is valuable, though if you're planning to go Voronoi so it doesn't flash even when there are some gaps between labels, then that alone may already fix the apparently multiplatform Chromium issue too.

**Comment by danyx23** [comment] 2023-01-02 19:01
Closing this. It would be nice but it's just not a priority.

**Closed by danyx23** 2023-01-02 19:01 UTC
Labels: enhancement, good first issue, ux
