### ISSUE TITLE
The y-axis minimum should default to zero for line charts

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#4065] opened 2024-10-16 11:48 UTC
/cc @maxroser 

## Problem

We give constant editorial feedback that authors should set the y-axis minimum to zero on line charts.

This is because this makes the chart more readable and sets changes in an indicator into their proper context and scale.

We should eliminate the need to give this feedback by simply defaulting to `yAxisMin` of 0.

## Examples

`db table chart_configs | where slug != null | get full | where yAxis.min != 0 and type == LineChart and hasChartTab == true | length`

380 charts are reported, including this random selection. Of those, 282 have `auto` set as the value.

- https://ourworldindata.org/grapher/share-of-land-that-is-protected-and-conserved
- https://ourworldindata.org/grapher/share-international-aviation-km
- https://ourworldindata.org/grapher/real-gdp-growth
- https://ourworldindata.org/grapher/annual-rate-of-change-in-urban-populations
- https://ourworldindata.org/grapher/agri-environmental-policies-intensity
- https://ourworldindata.org/grapher/share-of-events-with-a-mention-of-a-country
- https://ourworldindata.org/grapher/cumulative-number-of-large-scale-ai-systems-by-country
- https://ourworldindata.org/grapher/deaths-in-interstate-conflicts
- https://ourworldindata.org/grapher/india-government-debt-as-a-percentage-of-gdp-19802019
- https://ourworldindata.org/grapher/growth-rates-of-consumption-investment-and-gdp-in-india-1961-to-2020

## Proposed solution

- We set the default `yAxisMin` to 0
- We check a random sample of the 282 set to `auto` to confirm we are happy modifying them all automatically

**Comment by marcelgerber** [comment] 2024-10-16 12:42
Duplicate of #3797.

**Closed** 2024-10-16 14:00 UTC
Labels: feature, viz, needs triage, priority 2 - important
