### ISSUE TITLE
"Zoom to selection" doesn't work properly on "Weekly death growth rate vs. daily death rate"

### ISSUE THREAD

**Issue by doniks** [owid/owid-grapher#656] opened 2020-10-16 05:26 UTC
* navigate to the [chart](https://ourworldindata.org/grapher/weekly-death-growth-rate-vs-daily-death-rate?zoomToSelection=true&minPopulationFilter=1000000&time=latest&country=AUT~BOL~CUB~CZE~ISR~JAM~MEX~NLD~QAT~ROU~GBR~USA)
* untick "zoom to selection"
* -> y-axis goes up to ca 600% which is the largest value of all countries, independent of my selection of countries (Kyrgyzstan) : OK 
* tick "zoom to selection"
* -> y-axis goes up to 2500%. now most of the chart area is just empty, because everything is squished at the bottom: NOT OK

what I would expect is that the y-axis should go to 100% which is the largest value of any of the countries I have *selected* in "Select countries" (Mexico, Czech republic). x-axis should go to 6 instead of 25

I attach two screenshots

**Comment by doniks** [comment] 2020-10-16 05:28
![image](https://user-images.githubusercontent.com/26801304/96216609-068c7c00-0f81-11eb-92a3-f2dfc136e68e.png)
![image](https://user-images.githubusercontent.com/26801304/96216662-1c9a3c80-0f81-11eb-8594-2dd7bea89cd3.png)

**Comment by MarcelGerber** [comment] 2020-12-11 19:56
Hi @doniks, thank you for reporting this issue and sorry for leaving this hanging for so long!

We were aware of this problem already, and even though the problem is still present on ourworldindata.org, it is fixed in our internal build. I am therefore going to close this issue.

Again, thank you for your great bug report, the description and attached screenshots were very helpful!

**Closed by MarcelGerber** 2020-12-11 19:56 UTC

**Comment by doniks** [comment] 2021-01-04 05:10
Hi Marcel. Any idea when this might go live?
