### ISSUE TITLE
Intermittent and short `TypeError: Failed to fetch` appears on Grapher admin

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#3673] opened 2024-05-31 14:07 UTC
## Description

From time to time, there is an error appearing at random on Grapher admin. The error message says `TypeError: Failed to fetch` and it is commonly solved after refreshing. It is not problematic except when we are doing some changes before saving or when we modify a chart for a data insight and we have not exported.

## Expected behaviour

There should be no error message of this kind.

## Steps to reproduce

It can't be reproduced because it happens randomly, but if it is helpful, this error appeared for the last time on 31 May 2024, ~10:30, 10:35 AM in the UK (in case it can be observed in the log).

## Screenshots

From the last time it happened, while editing PNG and SVG exports for a DI.
![image](https://github.com/owid/owid-grapher/assets/63430031/ae29aa41-b435-4722-ad76-dbdbf3966e17)

## Environment

For desktop, provide:

-   OS: macOS Sonoma 14.5
-   Browser Chrome
-   Version 125.0.6422.113 (Official Build) (arm64)

## Additional context

[Original Slack post](https://owid.slack.com/archives/C46U9LXRR/p1717148199553539)

**Comment by danyx23** [comment] 2024-06-05 12:24
@paarriagadap are you on a wifi when these errors occur? My hunch would be that this is caused by some intermittent network issues. We could add an automatic retry logic though

**Comment by saloni-nd** [comment] 2024-06-05 12:53
Yeah it's hard for me to remember exactly when it happens, but I think it's usually been when I've had the tab open for a while and come back to it later on. I'll try to keep a look out for the next time it happens.

**Comment by paarriagadap** [comment] 2024-06-05 16:09
It happened many times today while showing Grapher to @antea04

**Comment by marcelgerber** [comment] 2024-06-19 13:20
We want to look into this, but don't currently have a good intuition as to what could be the problem.

It could be server restarts (because of OOM or other issues maybe?), but very much unsure about that.

It probably makes sense to look at this for, like, a day, and then see whether we could find a red herring somewhere.

**Comment by paarriagadap** [comment] 2024-06-19 13:23
Thanks @marcelgerber, I will post whenever this happens again, and the context around the error.

**Comment by marcelgerber** [comment] 2024-06-19 16:36
We now have a hunch that this might be related to Cloudflare Auth tokens running out.

**Comment by paarriagadap** [comment] 2024-06-21 09:46
Just happened once I returned to an admin tab to click "Datasets". It seems it's just like Saloni says, with tabs that are open for a while.
<img width="467" alt="image" src="https://github.com/owid/owid-grapher/assets/63430031/ec22ad36-3b00-45e9-9690-342da73aab04">

**Comment by paarriagadap** [comment] 2024-08-23 13:05
[Reported by Fiona](https://owid.slack.com/archives/C46U9LXRR/p1724416706868629).

> It’s not really urgent, but the frequency of this kind of error in admin seems to be gradually increasing. I don’t know if it’s fixable at all but sometimes it’s a little frustrating in chart admin, as it often comes up when you save changes, and those changes are then lost.

**Comment by danyx23** [comment] 2024-08-23 14:06
I just checked and it's repeatable that we get a not permitted reply. We'll have to work out how to refresh the CF auth token before we make requests in the admin if necessary. I'm bumping the priority of this up since it keeps bothering data managers and they loose work through this.

**Comment by rakyi** [comment] 2024-08-23 14:49
This seems to be caused by an extremely short session duration (15 min) set for the Grapher admin in Cloudflare. I bumped it to one week, let's see if that fixes it.

**Comment by paarriagadap** [comment] 2024-09-11 18:41
It seems we can close this issue? Thank you very much for the fix!

**Comment by rakyi** [comment] 2024-09-12 09:11
Indeed, closing!

**Closed by rakyi** 2024-09-12 09:11 UTC
Labels: bug, viz, priority 1 - essential, admin
