### ISSUE TITLE
Manually triggered deploy in staging gets stuck

### ISSUE THREAD

**Issue by rakyi** [owid/owid-grapher#3519] opened 2024-04-19 15:32 UTC
For example, unpublishing a gdocs post in staging triggers deployment that gets stuck in a loop. Error from `pm2 logs deploy-queue`:

```
11|deploy-queue  | 2024-04-19T14:44:18: Exception when executing SQL statement! {
11|deploy-queue  | 2024-04-19T14:44:18:   sql: '\n' +
11|deploy-queue  | 2024-04-19T14:44:18:     '                SELECT wpApiSnapshot FROM posts\n' +
11|deploy-queue  | 2024-04-19T14:44:18:     '                WHERE wpApiSnapshot IS NOT NULL\n' +
11|deploy-queue  | 2024-04-19T14:44:18:     '                AND status = "publish"\n' +
11|deploy-queue  | 2024-04-19T14:44:18:     '                AND type IN (?)\n' +
11|deploy-queue  | 2024-04-19T14:44:18:     "                ORDER BY wpApiSnapshot->>'$.date' DESC;\n" +
11|deploy-queue  | 2024-04-19T14:44:18:     '            ',
11|deploy-queue  | 2024-04-19T14:44:18:   params: [ [ 'post', 'page' ] ],
11|deploy-queue  | 2024-04-19T14:44:18:   error: TypeError: Cannot read properties of undefined (reading 'raw')
11|deploy-queue  | 2024-04-19T14:44:18:       at Object.knexRaw (/home/owid/owid-grapher/db/db.ts:113:47)
11|deploy-queue  | 2024-04-19T14:44:18:       at getPostsFromSnapshots (/home/owid/owid-grapher/db/model/Post.ts:184:67)
11|deploy-queue  | 2024-04-19T14:44:18:       at SiteBaker.removeDeletedPosts (/home/owid/owid-grapher/baker/SiteBaker.tsx:436:53)
11|deploy-queue  | 2024-04-19T14:44:18:       at SiteBaker.bakeAll (/home/owid/owid-grapher/baker/SiteBaker.tsx:1031:20)
11|deploy-queue  | 2024-04-19T14:44:18:       at triggerBakeAndDeploy (/home/owid/owid-grapher/baker/DeployUtils.ts:70:25)
11|deploy-queue  | 2024-04-19T14:44:18:       at Timeout.deployIfQueueIsNotEmpty (/home/owid/owid-grapher/baker/DeployUtils.ts:198:19)
11|deploy-queue  | 2024-04-19T14:44:18:
```

Manually restarting the full bake by removing `/home/owid/.site-baked` and hitting rebuild on the job in Buildkite works.

**Comment by danyx23** [comment] 2024-05-08 15:23
Let's monitor this but if the issue is not reported again by May 17 then we should probably just close it

**Comment by ikesau** [comment] 2024-05-08 15:29
Can confirm this is still happening - just ran a test content deploy by publishing a random article on a staging environment

**Closed** 2024-05-14 09:48 UTC
Labels: bug, priority 3 - nice to have
