### ISSUE TITLE
Marimekko charts show irrelevant legend, which disappears when adding an indicator for color

### ISSUE THREAD

**Issue by pabloarosado** [owid/owid-grapher#2961] opened 2023-11-29 13:50 UTC
## Description

Marimekko charts show irrelevant legend, which disappears when adding an indicator for color.

## Expected behaviour

When not selecting any variable for "color", [this marimekko chart](https://owid.cloud/admin/charts/5455/edit) shows an irrelevant legend. Then, this legend disappears when selecting a variable for "color". However, the color of the bars doesn't actually change. See demo in [this thread](https://owid.slack.com/archives/C46U9LXRR/p1701264479179209).

## Steps to reproduce

1. [Go to this marimekko chart](https://owid.cloud/admin/charts/5455/edit).
2. See the irrelevant legend.
3. Click to change the variable for "color" and unselect "Population", to leave it empty.
4. See that the legend disappears, but the color is not changed.

**Comment by sophiamersmann** [comment] 2024-01-09 07:35
duplicate of #2594

**Closed by sophiamersmann** 2024-01-09 07:35 UTC
Labels: bug, viz, needs triage
