### ISSUE TITLE
Tooltips on facets

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1181] opened 2022-02-17 10:29 UTC
Author: @CGiattino 
Author-rated priority: Medium
Completed?: No
Created on: December 6, 2021 11:14 PM
Description: Otherwise it's really hard to compare the facets
Last modified: January 5, 2022 12:28 PM
tags: Author request

## Motivation

The lack of this feature simply makes it harder to interpret faceted charts and identify country lines. Hannah indicated that for this reason, she sometimes chooses not to use faceted charts.

**Comment by danielgavrilov** [comment] 2022-02-17 10:33
Duplicate of #1084

**Closed by danielgavrilov** 2022-02-17 10:33 UTC
Labels: needs triage
