### ISSUE TITLE
Showing explorers in search results

### ISSUE THREAD

**Issue by saloni-nd** [owid/owid-grapher#2053] opened 2023-03-28 12:17 UTC
## Description
The explorers don't show up in search results - I don't know if this is a bug or intentional.

## Expected behaviour

I searched for "Global health explorer" and "Global health data explorer" and they didn't show up in the results, and also it wasn't on the Global health page, so I had to remember it was under Resources > Charts and Explorers to find it. 

I think this also affects the other explorers; I guess it's because the search results are only sections for 'Pages' and 'Charts' and explorers aren't either of those? But it makes it hard to find them, especially if they're not on the topic pages already (though I think that'll be fixed when we get through redesigning each of the Topic pages). Maybe there's some other way to make them show up in the search results?

## Screenshots

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/31684905/228232405-331c4229-1b4c-4c4f-be39-b2cace4fa0e9.png">

## Environment

For desktop, provide:

iOS Monterey; Chrome version 110.0.5481.77.

**Comment by marcelgerber** [comment] 2023-04-03 08:48
This is expected behaviour for now, but certainly not what we want.

There are several ways how we could go about that, from easy to hard:
- Surface explorers as links only, without preview (super easy)
- Surface explorers, and show their default view in the search results
- Surface explorers, and show the interactive explorer frame in search results (could still be quite easy to do, but not sure)
- Index _all explorer views_, and show them in search results, making sure to indicate that this is part of an explorer

Given that Project Search and navigation is currently underway, we will probably postpone this for a few more months, but should think about this during the design phase of the project.
cc @larsyencken @mathisonian.

However, we could certainly implement option 1 as a stopgap for now; it won't take long.

**Comment by larsyencken** [comment] 2023-07-24 19:52
Hey @ikesau, it looks like you've moved on from this. Did this one ship?

**Comment by ikesau** [comment] 2023-09-11 15:41
Merged in https://github.com/owid/owid-grapher/pull/2533

There are further improvements we could make (Description text, thumbnail preview) but let's make a new issue for that when we want it.

**Closed** 2023-09-25 09:47 UTC
Labels: bug, site, priority 2 - important, search
