### ISSUE TITLE
Failed to POST /api/importDataset (413)

### ISSUE THREAD

**Issue by flaxter** [owid/owid-grapher#976] opened 2021-07-28 19:15 UTC
Hi. Thanks for all of your hard work. We've got a stand-alone version for our orphanhood work here: https://imperialcollegelondon.github.io/orphanhood_trends

I went to update it today using the "Import CSV" feature and got the following:

![image](https://user-images.githubusercontent.com/59355/127381906-7f7108de-5297-4dda-b32c-e26c85df38fc.png)

After some poking around, I'm able to get around this cryptic error by dropping repeated observations, e.g.:

"country","date","orphanhood"
"Greece",552,154
"Greece",552,153

But this has an unwanted effect when visualized--I don't want "No data":

![image](https://user-images.githubusercontent.com/59355/127382360-ae2884e2-e3db-4825-b6c2-f2ef001f0410.png)

Here's an example CSV that gives me this error: 
[orphanhood.csv](https://github.com/owid/owid-grapher/files/6895943/orphanhood.csv)

**Comment by danielgavrilov** [comment] 2021-07-28 20:16
Hi @flaxter, impressive that you got this running!

First, our error handler doesn't format responses correctly, so the error you see has nothing to do with the actual error. You can see the actual error through DevTools → Network tab → the request that failed → Response. Or, I just also pushed [a patch](https://github.com/owid/owid-grapher/commit/1a926c8e572f7305cf8e681ad83d7376fb8bb181) to master that fixes this, and shows you the actual error.

Once you get the actual error, that might give us more of a clue. Right now this CSV uploads fine for me on a fresh setup, so I could not reproduce this. But there is a `UNIQUE` constraint on `(variableId, entityId, year)`, so having duplicate entries would result in errors. This shouldn't affect plots though, since two points can't be plotted for the same time & entity.

**Comment by danielgavrilov** [comment] 2021-07-28 20:23
There seem to be no duplicates in your uploaded CSV: https://colab.research.google.com/drive/1Cq2vHaof0ldXe9ZHi5v49moZ_hbY8rJt?usp=sharing

So possibly the problem is coming from somewhere else.

**Comment by flaxter** [comment] 2021-07-28 20:42
Thanks for the quick response! All credit for making this possible to @fvalka, who may have some questions about something he had to hack to get the share link to work.

Anyway, I've just reproduced it. No idea what was going on with the CSV duplicates or if that was really the culprit. It actually has to do with how we had to clone your setup, which involved some ssh tunneling. @fvalka knows the details. Anyway, accessing it through http://localhost:3030/admin/datasets/5369 (the ssh tunneling approach) made it work.

For future reference, I don't see DevTools → Network tab → the request that failed → Response...where should I like?

![image](https://user-images.githubusercontent.com/59355/127392952-4b0f8dd1-9fe8-4708-8a99-7471ae69e843.png)

**Comment by danielgavrilov** [comment] 2021-07-28 20:58
That's amazing @fvalka! Sorry we haven't really made your job easy there. 

@flaxter Sorry, DevTools is the tool web developers use, I made the assumption you are one. 🙂 How you open it varies across browsers. If you are on Chrome/Chromium, then Control + Shift + J should open it. Then going to the Network tab, you should see a list of requests. Anything red means there was an error (though there might be multiple). Clicking on an item in the list will open a pane which would contain a "Response" tab.

But all of this would be different in a different browser. And you need to have DevTools open _before_ the error happens, in order to capture the request in the Network list.

Anyway, I will close this issue since it seems to be resolved – let me know if it isn't or if you have other questions!

And if you make (or have made) anything else with our Grapher, we would be very curious to know!

**Closed by danielgavrilov** 2021-07-28 20:58 UTC
