### ISSUE TITLE
(TBC WIP) Chart exports (owid_chartdata, owid_metadata) broken

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1737] opened 2022-11-01 10:35 UTC
## Description

_These problems should be confirmed. Issue description is also preliminary and WIP_

- Problem 1: owid_chartdata.sql.gz and owid_metadata.sql.gz should be generated everyday, this seems to have stopped happening mid-October.
- Problem 2: even with the right owid_chartdata.sql.gz in S3, the refresh-staging script is not updating the DB "properly". Truncating the DB + reimporting manually from file on FS seem to import everything (two variables changed here, so need more investigation to narrow down the issue).

See inital debugging: https://owid.slack.com/archives/C46U9LXRR/p1667219006734249?thread_ts=1667069440.341449&cid=C46U9LXRR

## Screenshots

<img width="1220" alt="Screenshot 2022-11-01 at 11 24 36" src="https://user-images.githubusercontent.com/13406362/199213459-a709b1a2-1df9-4fe2-821a-ae1736d04973.png">

These should be updated every day at midnight. owid_chartdata in the screenshot has been updated by running the cron command manually.

**Comment by danyx23** [comment] 2022-11-01 16:52
This feels like it could be a canary in the coal mine - I suggest we prioritize checking if this looks like a bigger issue and give this high importance (basically verify that our backups in general are in place and functional). If this turns out to be just some annoying technical issue that makes updating staging servers to the latest data dump harder then it's not very urgent to fix it but it would still be nice to resolve this in this cycle I think.

**Comment by marcelgerber** [comment] 2022-11-19 14:53
I just confirmed that these backups indeed work again, and get pushed up to DO at midnight.

Fixed by https://github.com/owid/owid-grapher/commit/dfc79e135870100d4c079426ffdefd0e782606c7.

**Closed by marcelgerber** 2022-11-19 14:53 UTC
Labels: needs discussion, priority 2 - important
