### ISSUE TITLE
Syncing Wordpress -> Grapher (syncPostToGrapher) broken

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1742] opened 2022-11-02 17:13 UTC
## Description

The postUpdatedHook that syncs Wordpress posts to the grapher DB seems to have stopped working around mid-October. No more posts were being synced since that time.

This might be coincidental but another bug was recently surfaced from that same period: #1737 

## Expected behaviour

Posts are synced after being published, automatically (see Wordpress plugin for the trigger of that node script).

## Screenshots
Before running the manual `node syncPostsToGrapher.js` script

<img width="1440" alt="Screenshot 2022-11-02 at 18 04 42" src="https://user-images.githubusercontent.com/13406362/199555741-5855eaa1-c3d4-467d-9de4-426a43116888.png">

After running the manual `node syncPostsToGrapher.js` script

<img width="1440" alt="Screenshot 2022-11-02 at 18 06 19" src="https://user-images.githubusercontent.com/13406362/199556763-2df52c72-ca3e-49de-b235-3cb1c467982b.png">

## Impact

- Publishing still happens, meaning it doesn't affect the live site
- But the content graph comes out of sync
- Meaning that the content graph becomes an unreliable source of data
  - Could be a problem for prominent links

**Comment by larsyencken** [comment] 2022-11-07 12:39
This one might have been caused by node not running in cron. Now that we fixed that on `live`, I wonder if it's still an issue.

So far everything looks up to date. If it's also up-to-date after the next post goes out, let's close this as fixed.

**Comment by mlbrgl** [comment] 2022-11-09 08:18
> This one might have been caused by node not running in cron

The postUpdate hook doesn't run on cron, so that direct causality would surprise me but maybe what was done for `node` to run again in cron tangentially fixed this issue too (e.g. `node` running again in non-interactive shells would be a common denominator?).

**Comment by larsyencken** [comment] 2022-11-09 19:43
Hmm... it only changed for cron jobs, so if this wasn't happening via cron,
then it's probably not fixed.

**Comment by larsyencken** [comment] 2022-11-22 11:46
We confirmed that it's still happening and not fixed, @danyx23 said he'd check it out

**Comment by marcelgerber** [comment] 2022-11-23 11:26
It will be a similar thing as we had with cronjobs, where `node` is not defined in non-interactive shells.

One solution would be to symlink the nvm-provided to someplace, and then use that one throughout (making sure that we update the symlink whenever we update the node version we're using).

**Comment by danyx23** [comment] 2022-11-28 10:46
Fixed this now with the workaround of symlinking `/usr/local/bin/node` to `/home/owid/.nvm/versions/node/v16.13.2/bin/node`. This is brittle as we now have to remember updating this manually when we update node versions but there aren't any nice and easy solutions with nvm for doing this atm. We'll solve this differently when we move this away from the current server.

**Closed by danyx23** 2022-11-28 10:46 UTC
Labels: bug, priority 2 - important
