### ISSUE TITLE
Old COVID Explorer redirects are not working

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1119] opened 2022-01-31 10:33 UTC
## Description

Some of the COVID Explorer redirects specified in early 2021 have stopped working. Not all, just some.

Old Notion issue: [Old explorer redirects aren’t working](https://www.notion.so/owid/Old-explorer-redirects-aren-t-working-b1a6332b63ec4fc78d3ddbc32de556f5)

## Expected behaviour

The [specified redirects](https://github.com/owid/owid-grapher/blob/4683f5cb1fbec3048afed6180baa825891bfa98c/explorerAdminServer/ExplorerRedirects.ts#L4-L201) should continue to work.

## Steps to reproduce

1. Visit https://ourworldindata.org/grapher/covid-confirmed-daily-cases-epidemiological-trajectory
2. You get a 404, but the redirect is specified

## Analysis

It's not clear whether the redirect worked even in early 2021. We used to have Grapher charts for each redirect, and still do for some of them. It's possible that we only bake a redirect page if a Grapher with the slug exists? Not sure.

**Comment by larsyencken** [comment] 2022-02-07 13:50
Some people will have embedded our charts to make a certain point in their page. If we use Wordpress, we don't get the URL parameters passed through in the redirect, meaning especially that country and time selections can change for the embed.

We don't really know how many people this is affecting.

Theoretically, we could tackle redirects through CloudFlare workers. ~~We would need to cost it to understand if it would be a reasonable solution or not.~~ It costs PEANUTS!!!

But, some confusion re how it would work between CloudFlare and Netlify.

**Comment by larsyencken** [comment] 2022-02-25 11:43
I skimmed the old list, looks like these ones don't work:

- https://ourworldindata.org/grapher/daily-new-confirmed-cases-of-covid-19-per-million-tests-per-case 
- https://ourworldindata.org/grapher/daily-new-confirmed-cases-of-covid-19-tests-per-case 
- https://ourworldindata.org/grapher/total-tests-per-thousand-since-per-cap-death-threshold 
- https://ourworldindata.org/grapher/daily-covid-deaths-per-million-3-day-avg
- https://ourworldindata.org/grapher/daily-covid-cases-per-million-three-day-avg
- https://ourworldindata.org/grapher/coronavirus-cfr 
- https://ourworldindata.org/grapher/case-fatality-rate-covid-19 

I presume it only works when a grapher chart is baked. 

Although it's not ideal for these redirects to stop working, at the same time we have had no external complaints, so marking this as "won't fix". Any future ones we can just put into Wordpress, even though it's not ideal.

**Closed by larsyencken** 2022-02-25 11:43 UTC
Labels: bug, architecture
