### ISSUE TITLE
Some chart configs are missing `config.id` field

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#3015] opened 2023-12-12 16:43 UTC
## Description

Some recent charts are missing `charts.config.id` field. The field duplicates `charts.id` column, but we've always been using the one from config and we might rely on it in ETL (e.g. in chart revisions). We're ok if we stop population that field, but perhaps there might be other parts that rely on it?

## Expected behaviour

All charts should have `config.id`.

## Steps to reproduce

Run the following SQL to get all charts like that. Note that they've been created quite recently. There's about 20 charts like that now.

```sql
SELECT
  *
FROM charts
WHERE JSON_EXTRACT(config, '$.id') IS NULL;
```

Here are some of those charts
```
"consumer-price-index"
"cropland-area"
"thermal-efficiency-factor"
"renewable-nuclear-direct-substitution"
"deaths-from-snakebite-envenoming"
```

**Comment by marcelgerber** [comment] 2023-12-13 09:48
Think this is a duplicate of https://github.com/owid/owid-grapher/issues/2430.

**Comment by danyx23** [comment] 2024-03-20 15:23
Closing it as it is a duplicate of #2430.

**Closed by danyx23** 2024-03-20 15:23 UTC
Labels: bug, viz, needs triage
